### ISSUE TITLE
Unable to parse background-image

### ISSUE THREAD

**Issue by niemyjski** [AngleSharp/AngleSharp.Css#66]
# Bug Report

## Prerequisites

- [x] Can you reproduce the problem in a [MWE](https://en.wikipedia.org/wiki/Minimal_working_example)?
- [x] Are you running the latest version of AngleSharp?
- [x] Did you check the FAQs to see if that helps you?
- [x] Are you reporting to the correct repository? (there are multiple AngleSharp libraries, e.g., `AngleSharp.Css` for CSS support)
- [x] Did you perform a search in the issues?

For more information, see the `CONTRIBUTING` guide.

## Description

[Description of the bug]

I noticed that after painstakenly trying to upgrade from 0.9 to the latest release that some of my styles were completely removed. I stepped through the parser and found what I believe is a bug.

## Steps to Reproduce

Take the following CSS

```cs
using AngleSharp;
using AngleSharp.Css.Parser;

var css = @"
nav {
    background-color: #FFFFFF;
    background-image: -webkit-gradient(linear,left 50%,left bottom,from(#FFFFFF),to(#eeeeee));
    background-image: -moz-linear-gradient(top,#FFFFFF,#FFFFFF,#f8f8f8,#eeeeee);
    background-image: -ms-linear-gradient(top,#FFFFFF,#FFFFFF,#f8f8f8,#eeeeee);
    background-image: -o-linear-gradient(top,#FFFFFF,#FFFFFF,#f8f8f8,#eeeeee);
    background-image: linear-gradient(top,#FFFFFF,#FFFFFF,#f8f8f8,#eeeeee);
    background-image: -webkit-linear-gradient(top,#FFFFFF,#FFFFFF,#f8f8f8,#eeeeee);
    filter: progid:DXImageTransform.Microsoft.gradient(startColorStr='#FFFFFF',EndColorStr='#eeeeee');
}
";

var options = new CssParserOptions
{
    IsIncludingUnknownDeclarations = true,
    IsIncludingUnknownRules = true,
    IsToleratingInvalidSelectors = true
};
var context = BrowsingContext.New(Configuration.Default.WithCss(options));
var parser = new CssParser(options, context);
var parsed = parser.ParseStyleSheet(css);
```

**Expected behavior:** [What you expected to happen]
The above css rules are in the parsed result.

**Actual behavior:** [What actually happened]

```cs
nav { background-color: rgba(255, 255, 255, 1); filter: progid:DXImageTransform.Microsoft.gradient(startColorStr='#FFFFFF',EndColorStr='#eeeeee') }
```

**Environment details:** [OS, .NET Runtime, ...]
.NET 5, macOS (Latest)

## Possible Solution

I think there is a logic bug in CSSParser.FillDeclarations (https://github.com/AngleSharp/AngleSharp.Css/blob/5d034bfbbd5a8a6a851e135346fbcc5952173f2e/src/AngleSharp.Css/Parser/CssBuilder.cs#L453)

If you look at it it calls CollectTrivia (ignores whitespace etc..) so the first style shows up, then calls  `CreateDeclarationWith`(https://github.com/AngleSharp/AngleSharp.Css/blob/5d034bfbbd5a8a6a851e135346fbcc5952173f2e/src/AngleSharp.Css/Parser/CssBuilder.cs#L455) which is at a valid token. Then it  incorrectly calls CollectTrivia again. This happens in a loop of FillDeclarations to perfectly skip over valid rules.

**Comment by niemyjski** [comment]
Also, is there a case where I don't have to provide a context? And/or it feels pretty weird to have to specify the options twice when it's on the context.

**Comment by FlorianRappl** [comment]
I think your assumption is false. `CollectTrivia` is required to parse away potential comments and whitespaces. In case of non-trivia tokens it just returns.

If this would be the problem then most of the unit tests would be broken.

I think the problem is much more likely in the `linear-gradient` somewhat. If you replace that with, e.g., `url('foo.png')` it works better in the sense that the declaration is included.

In any case I think there is an issue here. Thanks for the report.

**Comment by FlorianRappl** [comment]
So yeah. The `linear-gradient` syntax is wrong. It need to be `to top` and not just `top`.

But since browsers still support this legacy syntax I've added it to AngleSharp.Css, too!

**Comment by niemyjski** [comment]
@FlorianRappl I upgraded to 0.15 and I ran the test above and it doesn't even emit the linear-gradient. The parsed content is:

```css
nav { 
  background-color: rgba(255, 255, 255, 1); 
  background-image: ; 
  filter: progid:DXImageTransform.Microsoft.gradient(startColorStr='#FFFFFF',EndColorStr='#eeeeee') 
}
```

**Comment by FlorianRappl** [comment]
> I'd expect the content to round trip.

HTML and CSS do not round trip. The serializations are not to preserve the original code, but rather to transport a serialization of its interpretation.

Regarding the issue: There is even a passing test for this (https://github.com/AngleSharp/AngleSharp.Css/blob/devel/src/AngleSharp.Css.Tests/Declarations/CssBackgroundProperty.cs#L701) so not sure what the problem here is. Feel free to dig into that. Contributions welcome!

**Comment by niemyjski** [comment]
@FlorianRappl: I took the following modified test and debugged it some more. I noticed that the test `CreateDeclarationWith` creates the proper value for each declaration. The `CreateValue` call returns a cached property and then sets value. This seems to be the root issue because `properties.SetProperty` gets the existing valid declaration, then runs the declaration value through a converter (which returns null for vendor prefixes (e.g., `webkit-`)), finally it overwrites the value.

```
        [Test]
        public void CssBackgroundImageNotParsed_Issue66_ordering_matters_fails()
        {
            var source = @"
background-image: linear-gradient(top,#FFFFFF,#FFFFFF,#f8f8f8,#eeeeee);
background-image: -webkit-linear-gradient(top,#FFFFFF,#FFFFFF,#f8f8f8,#eeeeee);";

            var property = ParseDeclaration(source);
            Assert.IsTrue(property.HasValue);

            var expected = "linear-gradient(0deg, rgba(255, 255, 255, 1), rgba(255, 255, 255, 1), rgba(248, 248, 248, 1), rgba(238, 238, 238, 1))";
            Assert.AreEqual(expected, property.Value);
        }
        
        [Test]
        public void CssBackgroundImageNotParsed_Issue66_ordering_matters_works()
        {
            var source = @"
background-image: -webkit-linear-gradient(top,#FFFFFF,#FFFFFF,#f8f8f8,#eeeeee);
background-image: linear-gradient(top,#FFFFFF,#FFFFFF,#f8f8f8,#eeeeee);";

            var property = ParseDeclaration(source);
            Assert.IsTrue(property.HasValue);

            var expected = "linear-gradient(0deg, rgba(255, 255, 255, 1), rgba(255, 255, 255, 1), rgba(248, 248, 248, 1), rgba(238, 238, 238, 1))";
            Assert.AreEqual(expected, property.Value);
        }
```

Seems like a fix may be if the value was not empty and the new value is empty don't set it? Previously to this issue it returned all the declarations.

**Comment by niemyjski** [comment]
@FlorianRappl Can you please reopen this issue.

**Comment by FlorianRappl** [comment]
I think the issue you posted is fixed. If you have a new issue / something else that is not working then please open another issue with a specific description.

Best case is that you also supply a PR that we can properly merge it in.

Thanks!

**Comment by niemyjski** [comment]
This wasn't fixed but I tried to dig into it without knowing the code base that well, I also added two tests above that could be copy and pasted.

**Comment by niemyjski** [comment]
^^ would it be possible to get the two tests I added to this project?
